weights: yolov5m.pt
cfg: ''
data: /home/oscar/Projects/Deep-Learning-for-Solar-Panel-Recognition/src/models/yolo/sp_dataset.yaml
hyp: src/models/yolo/yolov5/data/hyps/hyp.scratch.yaml
epochs: 10
batch_size: 48
imgsz: 256
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: 10
bucket: ''
cache: null
image_weights: false
device: cuda:0, cuda:1, cuda:2
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: src/models/yolo/yolov5/runs/evolve
name: yolov5m_10_test_hyp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: src/models/yolo/yolov5/runs/evolve/yolov5m_10_test_hyp2
